name: Bug report
description: Create a report to help us improve Pillow
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue.
        Follow these guidelines to ensure your issue is handled properly.

        If you have a ...

        1.  General question: consider asking the question on Stack Overflow
            with the [python-imaging-library tag].

            Do not ask a question in both places.

            If you think you have found a bug or have an unexplained exception
            then file a bug report here.

        2.  Bug report: include a self-contained, copy-pastable example that
            generates the issue if possible. Be concise with code posted.
            [Guidelines on how to provide a good bug report].
            Bug reports which follow these guidelines are easier to diagnose,
            and are often handled much more quickly.

        We know asking good questions takes effort, and we appreciate your time.

        Thank you.

        [python-imaging-library tag](https://stackoverflow.com/questions/tagged/python-imaging-library)
        [Guidelines on how to provide a good bug report](https://stackoverflow.com/help/mcve)
  - type: textarea
    attributes:
      label: What did you do?
      description: Please describe the steps to reproduce the issue.
      placeholder: placeholder...
    validations:
      required: true
  - type: textarea
    attributes:
      label: What did you expect to happen?
  - type: textarea
    attributes:
      label: What actually happened?
  - type: textarea
    attributes:
      label: What are your OS, Python and Pillow versions?
      value: |
        * OS:
        * Python:
        * Pillow:
  - type: input
    attributes:
      label: What is your operating system?
    validations:
      required: true
  - type: dropdown
    attributes:
      label: How did you install Pillow?
      options:
        - `pip install Pillow`
        - `conda install Pillow`
        - System package manager (e.g. `apt-get`, `yum`, ...)
        - Built from source
      default: 0
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the output of running `python3 -m PIL --report`?
      placeholder: |
        Please paste here the output of running `python3 -m PIL --report`,
        or the output of the following Python code:

        from PIL import features
        features.pilinfo(supported_formats=False)
  - type: textarea
    attributes:
      label: Additional information
      value: |
        <!--
        Please include **code** that reproduces the issue and whenever possible, an **image** that demonstrates the issue. Please upload images to GitHub, not to third-party file hosting sites. If necessary, add the image to a zip or tar archive.

        The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as Plone, Django, or Buildout, try to replicate the issue just using Pillow.
        -->

        ```python
        code goes here
        ```
