name: Test MSYS2

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - msystem: "CLANG64"
          - msystem: "MINGW64"
          # skip some subsystems to save CI time:
          # see https://github.com/python-pillow/Pillow/pull/6888#issuecomment-1400392821
          # - msystem: "UCRT64"
          # - msystem: "CLANG32"
          # - msystem: "MINGW32"

    defaults:
      run:
        shell: bash.exe --login -eo pipefail "{0}"
    env:
      MSYSTEM: ${{ matrix.msystem }}
      CHERE_INVOKING: 1

    timeout-minutes: 60
    name: MSYS2 ${{ matrix.msystem }}

    steps:
      - name: Checkout Pillow
        uses: actions/checkout@v3

      - name: Set up shell
        run: echo "C:\msys64\usr\bin\" >> $env:GITHUB_PATH
        shell: pwsh

      - name: Install dependencies
        run: |
          pacman -S --noconfirm make pactoys

          pacboy -S --noconfirm \
              freetype:p \
              gcc:p \
              ghostscript:p \
              lcms2:p \
              libimagequant:p \
              libjpeg-turbo:p \
              libraqm:p \
              libtiff:p \
              libwebp:p \
              openjpeg2:p \
              python3-cffi:p \
              python3-numpy:p \
              python3-olefile:p \
              python3-pip:p \
              python3-setuptools:p

          if [[ ${{ matrix.msystem }} =~ "64" ]]; then
              pacboy -S --noconfirm \
                  python-pyqt6:p
          fi

          python3 -m pip install pyroma pytest pytest-cov pytest-timeout

          pushd depends && ./install_extra_test_images.sh && popd

      - name: Build Pillow
        run: .ci/build.sh

      - name: Test Pillow
        run: .ci/test.sh

      - name: After success
        run: .ci/after_success.sh

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          flags: GHA_Windows
          name: MSYS2 ${{ matrix.msystem }}
          gcov: true

  success:
    permissions:
      contents: none
    needs: build
    runs-on: ubuntu-latest
    name: MinGW Test Successful
    steps:
      - name: Success
        run: echo MinGW Test Successful
